feat: Add function to set user's shell
refactor: Add err() function for convenience

refactor: Use grep -o instead of perl to parse ldd paths

feat: Add error handling for commands

diff --git a/security-engineering/final_project/setup-chroot-jail b/security-engineering/final_project/setup-chroot-jail
--- a/security-engineering/final_project/setup-chroot-jail
+++ b/security-engineering/final_project/setup-chroot-jail
@@ -1,4 +1,5 @@
 #!/bin/bash
+# shellcheck disable=SC2120
 
 # TODO(improvements): 
 #    - Use 'install' instead of 'cp' for copying binaries
@@ -12,11 +13,21 @@
 #       - iptables/nftables rule to restrict jailed user to SSH only to certain hosts
 #   - Use readonly bind mount?
 
+# TODO(feat): 
+#   - Parse SSH config script and somehow present those choices to user in bastion.sh
+#       - Parsing must happen in setup.
+#       - Can not happen in bastion script due to limited binary access (no sed,awk,perl)
+
 declare CHROOT_DIR='/var/chroot'
 declare JAILED_USER='juvie'
 declare BASTION_HOST_IP='192.168.4.74'
+declare BASTION_SCRIPT='bastion.sh'
 
-declare -a BINARIES=("rbash" "ssh")
+declare -a BINARIES=(
+    "rbash"
+    "ssh"
+    "ping"
+)
 
 declare -a SYSFILES=(
     "/etc/passwd"
@@ -26,7 +37,7 @@ declare -a SYSFILES=(
 )
 
 declare -a SPECIAL_FILES=(
-    "/dev/null "
+    "/dev/null"
     "/dev/tty" 
     "/dev/zero"
     "/dev/random"
@@ -34,11 +45,25 @@ declare -a SPECIAL_FILES=(
 )
 
 declare VERBOSE=0
+
+debug() {
+    [[ $VERBOSE -gt 0 ]] && printf "[\033[33m DEBUG \033[0m]: %s\n" "$@"
+}
+
+err() {
+    printf >&2 "[\033[31m ERROR \033[0m]: "
+    if [[ $# -gt 0 ]]; then
+        printf "%s\n" "$*"
+    fi
+}
+
+
+
 while [[ -n $1 ]]; do
     case $1 in
         -c|--chroot-dir)
             { [[ -n $2 && ! $2 =~ ^- ]] && shift && CHROOT_DIR=$1; } || {
-                printf "\033[31m"; printf >&2 "The -c/--chroot-dir option was given with no valid argument.\n"
+                err; printf >&2 "The -c/--chroot-dir option was given with no valid argument.\n"
                 exit 1
             }
             printf "Chroot directory set to %s\n" "$CHROOT_DIR"
@@ -48,6 +73,9 @@ while [[ -n $1 ]]; do
             VERBOSE=1
             shift;
             ;;
+        -s|--script)
+            [[ -n $2 ]] && shift && BASTION_SCRIPT=$2 || printf >&2 "No valid argument passed to -s/--script\n"
+            ;;
         -h|--help)
             # TODO: Add help text
             :
@@ -55,22 +83,19 @@ while [[ -n $1 ]]; do
     esac
 done
 
-debug() {
-    [[ -n $VERBOSE ]] && printf "[\033[33m DEBUG \033[0m]: %s\n" "$@"
-}
 
 setup-chroot-dir() {
 
     printf "Setting up directory structure.\n"
 
     # sudo mkdir -p ${CHROOT_DIR}/{bin,lib,dev,etc,home,usr/bin,lib/x86_64-linux-gnu} || {
-    #     printf "\033[31m"; printf >&2 "Failed to create directory tree for chroot jail!\n"
+    #     err; printf >&2 "Failed to create directory tree for chroot jail!\n"
     # }
 
-    for dir in {bin,lib,dev,etc,home,usr/bin,lib/x86_64-linux-gnu}; do
+    for dir in {bin,lib,lib64,dev,etc,home,usr/bin,lib/x86_64-linux-gnu}; do
         if ! [[ -d ${CHROOT_DIR}/$dir ]]; then
             sudo mkdir -p "${CHROOT_DIR}/$dir" || {
-                printf "\033[31m"; printf >&2 "Failed to create directory tree for chroot jail!\n" && return 1
+                err; printf >&2 "Failed to create directory tree for chroot jail!\n" && return 1
             }
         else
             debug "Directory already exists, skipping: $dir"
@@ -82,7 +107,8 @@ setup-chroot-dir() {
         if [[ ! -d  "${CHROOT_DIR}$(dirname "$SYSFILE")" ]]; then
             printf "Creating directory for %s at %s\n" "$SYSFILE" "$CHROOT_DIR/$(basename "$SYSFILE")"
             sudo mkdir -p "$(dirname "$SYSFILE")" || {
-                printf "\033[31m"; printf >&2 "Failed to make directory for %s at %s\n" "$SYSFILE" "$(dirname "$SYSFILE")"
+                err;
+                printf >&2 "Failed to make directory for %s at %s\n" "$SYSFILE" "$(dirname "$SYSFILE")"
             }
         fi
 
@@ -95,20 +121,19 @@ setup-chroot-dir() {
         debug "Copying binary: ${BINARY}"
         BIN_PATH=$(which "$BINARY")
         sudo cp "$BIN_PATH" "${CHROOT_DIR}${BIN_PATH}" || {
-            printf "\033[31m"; printf >&2 "Failed to copy binary (%s) to destination: %s\n" "$BINARY" "${CHROOT_DIR}${BIN_PATH}"
+            err; printf >&2 "Failed to copy binary '%s' to destination: %s\n" "$BINARY" "${CHROOT_DIR}${BIN_PATH}"
         }
 
         # Gather Link Libraries for the binary
         local -a BIN_LLIBS
-        IFS=$'\n' read -r -d '' -a BIN_LLIBS < <(ldd "$BIN_PATH" |
-            perl -ne 'print $1 . "\n" if s/^[^\/]*(\/.*)\(.*$/\1/')
-            # grep -o '/[^ ]*'
+        IFS=$'\n' read -r -d '' -a BIN_LLIBS < <(ldd "$BIN_PATH" | grep -o '/[^ ]*' )
+            # perl -ne 'print "$1\n" if s/^[^\/]*(\/.*)\s*\(.*$/\1/')
 
-        printf "LLIB for %s: %s\n" "$BINARY" "${BIN_LLIBS[@]}"
         for LLIB in "${BIN_LLIBS[@]}"; do
+            debug "LLIB for $BINARY - ${LLIB}"
             if ! stat "${CHROOT_DIR}${LLIB}" > /dev/null 2>&1; then
                 sudo cp "${LLIB}" "${CHROOT_DIR}${LLIB}" || {
-                    printf "\033[31m"; printf >&2 "Failed to copy linked library (%s) to destination: %s" \
+                    err; printf >&2 "Failed to copy linked library '%s' to destination: %s" \
                         "$LLIB" \
                         "${CHROOT_DIR}${LLIB}"
                 }
@@ -128,12 +153,12 @@ setup-chroot-dir() {
 
             read -r -d '' -a MAJOR_MINOR < <(
                 awk '/Device type/ {print $(NF)"\n"}' < <(stat "$SPECIAL_FILE") | tr ',' ' '
-            )
+            ) 
+
+            debug "$SPECIAL_FILE - Major: ${MAJOR_MINOR[0]}, Minor: ${MAJOR_MINOR[1]}"
 
             sudo mknod -m 666 "${CHROOT_DIR}${SPECIAL_FILE}" c "${MAJOR_MINOR[@]}" || { 
-                printf "\033[31m"; printf >&2 "Failed to create character special file: %s\n" "${SPECIAL_FILE}";
-                printf "\033[0m"
-                return 1
+                err; printf >&2 "Failed to create character special file: %s\n" "${SPECIAL_FILE}";
             }
 
         else
@@ -144,57 +169,74 @@ setup-chroot-dir() {
     # Copy name switch service files for network functionality
     printf "Copying Name Switch Service (NSS) files.\n"
     sudo cp -r /lib/x86_64-linux-gnu/*nss* "$CHROOT_DIR/lib/x86_64-linux-gnu" || {
-        printf "\033[31m"; printf >&2 "Failed to copy name switch service files!\n"
+        err; printf >&2 "Failed to copy name switch service files!\n"
     }
 
 }
 
 setup-jailed-user() {
+    local PASSWORD=
+
     if [[ $(hostname -I | awk '{print $1}' | tr -d ' ') != "$BASTION_HOST_IP" ]]; then
-        printf "\033[31m"; printf >&2 "Your localhost is not the targeted bastion host.\n" 
-        printf "\033[0m"
-        return 1
+        err; printf >&2 "Your localhost is not the targeted bastion host.\n" 
     fi
+
     sudo useradd -m "${JAILED_USER}" || {
-        printf "\033[31m"; printf >&2 "Failed to add jailed user account!\n" 
-        printf "\033[0m"
+        err; printf >&2 "Failed to add jailed user account!\n" 
         return 1
     }
-    printf "User account %s succussfully added.\n" "$JAILED_USER"
 
-    local PASSWORD=
+    printf "User account %s succussfully added.\n" "$JAILED_USER"
     read -r -s -p "Enter password for user account: " PASSWORD || {
-        printf "\033[31m"; printf >&2 "Failed to read password for user: %s\n" "$JAILED_USER"
-        printf "\033[0m"
+        err; printf >&2 "Failed to read password for user: %s\n" "$JAILED_USER"
     }
 
     printf "Setting password for user: %s\n" "${JAILED_USER}"
     printf "%s\n%s\n" "$PASSWORD" "$PASSWORD" | sudo passwd "${JAILED_USER}" || {
-        printf "\033[31m"; printf >&2 "Failed to set password for user: %s\n" "$JAILED_USER" 
-        printf "\033[0m"
+        err; printf >&2 "Failed to set password for user: %s\n" "$JAILED_USER" 
         return 1
     }
+}
 
+configure-user-shell(){
+
+    if ! [[ -f "./${BASTION_SCRIPT}" ]]; then
+        err; printf >&2 "There's no bastion script to copy in the current directory!\n" && return 1
+    else
+        sudo cp "./$BASTION_SCRIPT" "${CHROOT_DIR}/bin/${BASTION_SCRIPT}" || {
+            err;printf >&2 "Failed to copy %s to %s/bin/%s" "$BASTION_SCRIPT" "$CHROOT_DIR" "$BASTION_SCRIPT"
+            return 1
+        }
+        debug "Successfully copied ${BASTION_SCRIPT} to ${CHROOT_DIR}/bin/${BASTION_SCRIPT}."
+
+        sudo sed -iE "/${JAILED_USER}/s,/bin/b\?a\?sh,/bin/${BASTION_SCRIPT}," /etc/passwd || {
+            err;printf >&2 "Failed to replace default shell in /etc/passwd! \n" && return 1
+        }
+        debug "Successfully added ${BASTION_SCRIPT} as shell for ${JAILED_USER}."
+    fi
+    return 0
 }
 
 configure-ssh(){
+
     # Set up the bastion script and rules for the jailed user
+
     if ! grep -qi "Match User ${JAILED_USER}" /etc/ssh/sshd_config; then
         {
-	    cat <<- EOF | sudo tee -a /etc/ssh/sshd_config
+	    cat <<- EOF | sudo tee -a /etc/ssh/sshd_config > /dev/null 2>&1
 		Match User $JAILED_USER
 		    ChrootDirectory $CHROOT_DIR
 		    PasswordAuthentication yes
 		    AuthenticationMethods password
 		EOF
         } || {
-            printf "\033[31m"; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" 
-            printf "\033[0m"
+            err; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" 
             return 1
         }
+
         # sudo sed -i -E "\$a Match User ${JAILED_USER}\nChrootDirectory ${CHROOT_DIR}\n" \
         #     /etc/ssh/sshd_config || {
-        #     printf "\033[31m"; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" && return 1
+        #     err; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" && return 1
         # }
 
         printf "Added ChrootDirectory rule for %s\n" "$JAILED_USER"
@@ -205,39 +247,40 @@ configure-ssh(){
     printf "Restarting SSH daemon...\n"
 
     sudo systemctl restart ssh || {
-        printf "\033[31m"; printf >&2 "Failed to restart SSH!\n"
-        printf "\033[0m"
+        err; printf >&2 "Failed to restart SSH!\n"
         return 1
     }
+    printf "\033[32mSuccessfully restarted SSH!\033[0m\n"
 
 }
 
-    
-printf "Setting up chroot jail environment in: %s\n" "$CHROOT_DIR"
-
-setup-chroot-dir || {
-    printf "\033[31m"; printf >&2 "Failed to set up chroot directory!\n"; printf "\033[0m" 
-    exit 1
-}
-
-printf "\033[32mSuccessfully set up chroot directory in %s\033[0m\n" "$CHROOT_DIR"
+# User account setup
 printf "Attempting to set up a user account for jailed user: %s\n" "$JAILED_USER"
-
 setup-jailed-user || {
-    printf "\033[31m"; printf >&2 "Failed to set up jailed user!\n" && exit 1
+    err; printf >&2 "Failed to set up jailed user!\n" && exit 1
 }
-
 printf "\033[32mSuccessfully set up jailed user: %s\033[0m\n" "$JAILED_USER"
-printf "Attempting to configure SSH rules for jailed user.\n"
 
-configure-ssh || {
-    printf "\033[31m"
-    printf >&2 "Failed to configure ssh rules for jailed user!\n"; 
-    printf "\033[0m" 
+# Directory setup
+printf "Setting up chroot jail environment in: %s\n" "$CHROOT_DIR"
+setup-chroot-dir || {
+    err; printf >&2 "Failed to set up chroot directory!\n"; 
     exit 1
-
 }
+printf "\033[32mSuccessfully set up chroot directory in %s\033[0m\n" "$CHROOT_DIR"
 
+# User shell setup
+printf "Attempting to configure user's shell...\n"
+configure-user-shell || {
+    err;printf >&2 "Failed to set up user's shell to %s\n" "$BASTION_SCRIPT"
+}
+printf "\033[32mSuccessfully set up user's shell!\033[0m\n"
+
+# SSH configuration
+printf "Attempting to configure SSH rules for jailed user.\n"
+configure-ssh || {
+    err; printf >&2 "Failed to configure ssh rules for jailed user!\n"; exit 1
+}
 printf "\033[32mSuccessfully set up jailed user.\033[0m\n"
 
 
