feat: Parse SSH config file into destinations.txt

diff --git a/security-engineering/final_project/setup-chroot-jail b/security-engineering/final_project/setup-chroot-jail
--- a/security-engineering/final_project/setup-chroot-jail
+++ b/security-engineering/final_project/setup-chroot-jail
@@ -26,6 +26,10 @@ declare CHROOT_DIR='/var/chroot'
 declare JAILED_USER='juvie'
 declare BASTION_HOST_IP='192.168.4.74'
 declare BASTION_SCRIPT='bastion.sh'
+declare LOG_FILE='./chroot-setup.log'
+declare DESTINATIONS_OUTPUT_FILE="$CHROOT_DIR/destinations.txt"
+
+# exec > "$LOG_FILE"
 
 declare -a BINARIES=(
     "rbash"
@@ -57,7 +61,7 @@ debug() {
 err() {
     printf >&2 "[\033[31m ERROR \033[0m]: "
     if [[ $# -gt 0 ]]; then
-        printf "%s\n" "$*"
+        printf >&2 "%s\n" "$*"
     fi
 }
 
@@ -237,12 +241,6 @@ configure-ssh(){
             err; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" 
             return 1
         }
-
-        # sudo sed -i -E "\$a Match User ${JAILED_USER}\nChrootDirectory ${CHROOT_DIR}\n" \
-        #     /etc/ssh/sshd_config || {
-        #     err; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" && return 1
-        # }
-
         printf "Added ChrootDirectory rule for %s\n" "$JAILED_USER"
     else
         printf "Entry already found in /etc/ssh/sshd_config. Skipping.\n"
@@ -257,6 +255,18 @@ configure-ssh(){
     printf "\033[32mSuccessfully restarted SSH!\033[0m\n"
 
 }
+
+parse-ssh-file() {
+    if [[ -f ~/.ssh/config && -f ./generate-destinations ]]; then
+        ./generate-destinations -f ~/.ssh/config -o "$DESTINATIONS_OUTPUT_FILE" || {
+            printf >&2 "Error in destination generation script!\n" && return 1
+        }
+    else
+        printf >&2 "No SSH file to parse for destinations!\n" && return 1
+    fi
+    return 0
+}
+
 
 # User account setup
 printf "Attempting to set up a user account for jailed user: %s\n" "$JAILED_USER"
@@ -283,7 +293,16 @@ printf "\033[32mSuccessfully set up user's shell!\033[0m\n"
 # SSH configuration
 printf "Attempting to configure SSH rules for jailed user.\n"
 configure-ssh || {
-    err; printf >&2 "Failed to configure ssh rules for jailed user!\n"; exit 1
+    err; printf >&2 "Failed to configure ssh rules for jailed user!\n"; exit 1;
 }
 printf "\033[32mSuccessfully set up jailed user.\033[0m\n"
+
+printf "Attempting to generate destinations based on SSH config.\n"
+parse-ssh-file || {
+    err; printf >&2 "Failed to parse ssh file.\n"; exit 1;
+}
+printf "\033[32mSuccessfully generated destinations file at: %s\033[0m\n" "$DESTINATIONS_OUTPUT_FILE"
+
+
+
 
